services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    ports: 
      - "5432:5432"
    volumes:
      - volume_1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 3s
      retries: 5

  # migration:
  #   build: .
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: migrate -path ./migrations/ -database ${DB_URL} up


volumes:
  volume_1:
